sudo: required
dist: trusty

language: go

go:
  - 1.5

# caveat:
# no glfw3 on ubuntu trusty so can not build windowing stuff
# must add every new package manually
script:
  - go build -v . ./examples/thirddraw ./examples/thirdrender
  - go test -v .
